namespace MoreInjuries.HealthConditions.Secondary.Handlers;

public class HediffCompHandler_SecondaryCondition_PostMake : HediffCompHandler_SecondaryCondition, IHediffComp_SecondaryCondition_PostMakeHandler;
