namespace MoreInjuries.Localization;

public static class Named
{
    /// <summary>
    /// A non-exhaustive list of commonly-used named paramter labels for translation.
    /// </summary>
    public static class Params
    {
        public const string THING = nameof(THING);
        public const string PATIENT = nameof(PATIENT);
        public const string PATIENTNAME = nameof(PATIENTNAME);
        public const string DOCTOR = nameof(DOCTOR);
        public const string DOCTORNAME = nameof(DOCTORNAME);
        public const string BODYPART = nameof(BODYPART);
        public const string PAWN = nameof(PAWN);
        // time
        public const string TIME = nameof(TIME);
        public const string DAYS = nameof(DAYS);
        public const string HOURS = nameof(HOURS);
        public const string SECONDS = nameof(SECONDS);
        // misc
        public const string VALUE = nameof(VALUE);
        public const string PERCENT = nameof(PERCENT);
        public const string DEFAULT = nameof(DEFAULT);
    }

    /// <summary>
    /// A non-exhaustive list of translation keys that are used in more than one place.
    /// By contract, any translation key that is used in more than one place must be defined here.
    /// </summary>
    public static class Keys
    {
        // NOTE: please use in-line xml comments to document the purpose of each key
        // they may be generated by running the following regex-replace ON THIS DOCUMENT ONLY:
        // Find: ///\s+<summary>\r?\n\s+///\s+([^\r\n]+)\r?\n\s+///\s+</summary>
        // Replace: /// <summary>$1</summary>

        /// <summary>{TIME_HOURS}h</summary>
        public static string Format_TimeHours => "MI_Format_TimeHours";

        /// <summary>{TIME_DAYS}d</summary>
        public static string Format_TimeDays => "MI_Format_TimeDays";

        /// <summary>{0} (from inventory)</summary>
        public static string Procedure_FromInventory => "MI_Procedure_FromInventory";

        /// <summary>{0} (stabilize)</summary>
        public static string Procedure_Stabilize => "MI_Procedure_Stabilize";

        /// <summary>{0} (fully heal)</summary>
        public static string Procedure_FullyHeal => "MI_Procedure_FullyHeal";

        /// <summary>{0} (from inventory, stabilize)</summary>
        public static string Procedure_FromInventory_Stabilize => "MI_Procedure_FromInventory_Stabilize";

        /// <summary>{0} (from inventory, fully heal)</summary>
        public static string Procedure_FromInventory_FullyHeal => "MI_Procedure_FromInventory_FullyHeal";

        /// <summary>{0}: medical care for {PATIENT_labelShort} disabled</summary>
        public static string ProcedureFailed_CareDisabled => "MI_ProcedureFailed_CareDisabled";

        /// <summary>{0}: {DOCTOR_labelShort} is incapable of manipulation</summary>
        public static string ProcedureFailed_IncapableOfManipulation => "MI_ProcedureFailed_IncapableOfManipulation";

        /// <summary>{0}: {DOCTOR_labelShort} is blind</summary>
        public static string ProcedureFailed_IncapableOfSight => "MI_ProcedureFailed_IncapableOfSight";

        /// <summary>{0}: {DOCTOR_labelShort} is incapable of caring</summary>
        public static string ProcedureFailed_IncapableOfCaring => "MI_ProcedureFailed_IncapableOfCaring";

        /// <summary>{0}: {DOCTOR_labelShort} is incapable of medicine</summary>
        public static string ProcedureFailed_IncapableOfMedicine => "MI_ProcedureFailed_IncapableOfMedicine";

        /// <summary>{0}: self-tend is disabled</summary>
        public static string ProcedureFailed_SelfTendDisabled => "MI_ProcedureFailed_SelfTendDisabled";

        /// <summary>After the procedure, {DOCTOR_labelShort} noticed that the {THING_label} has broken down and needs to be replaced.</summary>
        public static string Message_ProcedureIngredientDestroyed => "MI_Message_ProcedureIngredientDestroyed";
    }
}
