using Microsoft.CodeAnalysis.CSharp;
using MoreInjuries.Roslyn.SourceGen.Extensions;
using MoreInjuries.Roslyn.SourceGen.XmlSerialization.Attributes;
using System.Runtime.CompilerServices;
using System.Text;

namespace MoreInjuries.Roslyn.SourceGen.XmlSerialization;

internal static class XmlSerialiableRenderer
{
    private static readonly string s_throwHelperPrefix = $"global::{typeof(XmlFieldThrowHelper).FullName}";

    public static string Render(XmlSerializableGenerationModel model)
    {
        StringBuilder sourceBuilder = new(
            $$"""
            // <auto-generated/>
            #nullable enable

            {{RenderNamespace(model.Namespace)}}
            partial class {{model.ClassName}}
            {

            """);

        IndentedStringBuilder indentedBuilder = new(sourceBuilder, indentLevel: 1);
        BuildFieldRegion(model, indentedBuilder);
        indentedBuilder.Raw.AppendLine();
        sourceBuilder.AppendLine("#pragma warning disable CS0618 // generated property accessors reference [Obsolete] backing fields");
        BuildPropertyRegion(model, indentedBuilder);
        sourceBuilder.AppendLine("#pragma warning restore CS0618");
        sourceBuilder.AppendLine("}");

        return sourceBuilder.ToString();
    }

    private static void BuildFieldRegion(XmlSerializableGenerationModel model, IndentedStringBuilder builder)
    {
        foreach (XmlMemberModel member in model.AnnotatedMembers)
        {
            string readonlyModifier = member.HasSetter && !member.IsInitOnly ? "" : "readonly ";
            string defaultExpression = GetDefaultExpression(member);

            builder.AppendLine($"[global::{typeof(CompilerGeneratedAttribute).FullName}]");
            if (!member.AllowRawAccess)
            {
                builder.AppendLine($"[global::{typeof(ObsoleteAttribute).FullName}(\"Do not use this field directly. Use the corresponding property instead.\", error: false)]");
            }
            builder.AppendLine($"private {readonlyModifier}{member.FieldTypeDisplay} {member.FieldName} = {defaultExpression};");
        }
    }

    private static void BuildPropertyRegion(XmlSerializableGenerationModel model, IndentedStringBuilder builder)
    {
        string className = model.ClassName;

        foreach (XmlMemberModel member in model.AnnotatedMembers)
        {
            string accessKeyword = SyntaxFacts.GetText(member.PropertyAccessibility);
            string modifiers = member.PropertyModifiers;
            bool needsBlockGetter = member.ValidateMethodName is not null || member.TransformMethodName is not null;

            if (!member.HasSetter && !needsBlockGetter)
            {
                // Simple getter-only: expression-bodied property
                string getterExpression = GetGetterExpression(member, className);
                builder.AppendLine($"{accessKeyword} {modifiers}partial {member.PropertyTypeDisplay} {member.PropertyName} => {getterExpression};");
            }
            else
            {
                // Block body property
                builder.AppendLine($"{accessKeyword} {modifiers}partial {member.PropertyTypeDisplay} {member.PropertyName}");
                builder.AppendLine("{");
                IndentedStringBuilder inner = builder.IncreaseIndent();

                if (needsBlockGetter)
                {
                    BuildBlockGetter(inner, member, className);
                }
                else
                {
                    string getterExpression = GetGetterExpression(member, className);
                    inner.AppendLine($"get => {getterExpression};");
                }

                if (member.HasSetter)
                {
                    string setterAccessKeyword = member.SetterAccessibility != member.PropertyAccessibility
                        ? SyntaxFacts.GetText(member.SetterAccessibility) + " "
                        : "";
                    string setOrInit = member.IsInitOnly ? "init" : "set";
                    string valueExpression = member.SetterCastType is { } castType
                        ? $"({castType})value"
                        : "value";
                    inner.AppendLine($"{setterAccessKeyword}{setOrInit} => this.{member.FieldName} = {valueExpression};");
                }

                builder.AppendLine("}");
            }
        }
    }

    private static void BuildBlockGetter(IndentedStringBuilder builder, XmlMemberModel member, string className)
    {
        builder.AppendLine("get");
        builder.AppendLine("{");
        IndentedStringBuilder inner = builder.IncreaseIndent();

        // Step 1: get base value (with null-check if needed)
        string baseExpression = GetGetterExpression(member, className);
        inner.AppendLine($"{member.PropertyTypeDisplay} __value = {baseExpression};");

        // Step 2: apply Transform if specified
        if (member.TransformMethodName is { } transform)
        {
            string callPrefix = member.TransformIsStatic ? "" : "this.";
            inner.AppendLine($"__value = {callPrefix}{transform}(__value);");
        }

        // Step 3: apply Validate if specified
        if (member.ValidateMethodName is { } validate)
        {
            string callPrefix = member.ValidateIsStatic ? "" : "this.";
            inner.AppendLine($"if (!{callPrefix}{validate}(__value))");
            inner.AppendLine("{");
            IndentedStringBuilder throwInner = inner.IncreaseIndent();
            throwInner.AppendLine($"{s_throwHelperPrefix}.{nameof(XmlFieldThrowHelper.FailedValidation)}(\"{className}\", \"{member.PropertyName}\");");
            inner.AppendLine("}");
        }

        inner.AppendLine("return __value;");
        builder.AppendLine("}");
    }

    private static string GetDefaultExpression(XmlMemberModel member)
    {
        if (member.DefaultValueExpression is { } defaultValue)
        {
            return defaultValue;
        }
        // Nullable fields (either naturally nullable or made nullable for null-check) use `default`
        // Value types also use `default` (which is the zero-value)
        return "default";
    }

    private static string GetGetterExpression(XmlMemberModel member, string className)
    {
        if (!member.RequiresNullCheck)
        {
            return $"this.{member.FieldName}";
        }
        if (member.IsStringType)
        {
            return $"{s_throwHelperPrefix}.{nameof(XmlFieldThrowHelper.NotNullOrEmpty)}(this.{member.FieldName}, \"{className}\")";
        }
        return $"{s_throwHelperPrefix}.{nameof(XmlFieldThrowHelper.NotNull)}(this.{member.FieldName}, \"{className}\")";
    }

    private static string RenderNamespace(string namespaceName) =>
        string.IsNullOrWhiteSpace(namespaceName)
            ? string.Empty
            : $"namespace {namespaceName};\n";
}
