using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using MoreInjuries.Roslyn.SourceGen.Extensions;
using MoreInjuries.Roslyn.SourceGen.XmlSerialization.Attributes;
using System.Runtime.CompilerServices;
using System.Text;

namespace MoreInjuries.Roslyn.SourceGen.XmlSerialization;

internal static class XmlSerialiableRenderer
{
    private static readonly string s_throwHelperPrefix = $"global::{typeof(XmlFieldThrowHelper).FullName}";

    public static string Render(XmlSerializableGenerationModel model)
    {
        StringBuilder sourceBuilder = new(
            $$"""
            // <auto-generated/>
            #nullable enable

            {{RenderNamespace(model.Namespace)}}
            partial class {{model.ClassName}}
            {

            """);

        IndentedStringBuilder indentedBuilder = new(sourceBuilder, indentLevel: 1);
        BuildFieldRegion(model, indentedBuilder);
        indentedBuilder.Raw.AppendLine();
        BuildPropertyRegion(model, indentedBuilder);
        sourceBuilder.AppendLine("}");

        return sourceBuilder.ToString();
    }

    private static void BuildFieldRegion(XmlSerializableGenerationModel model, IndentedStringBuilder builder)
    {
        foreach (XmlMemberModel member in model.AnnotatedMembers)
        {
            string readonlyModifier = member.HasSetter && !member.IsInitOnly ? "" : "readonly ";
            string defaultExpression = GetDefaultExpression(member);

            builder.AppendLine($"[global::{typeof(CompilerGeneratedAttribute).FullName}]");
            builder.AppendLine($"private {readonlyModifier}{member.FieldTypeDisplay} {member.FieldName} = {defaultExpression};");
        }
    }

    private static void BuildPropertyRegion(XmlSerializableGenerationModel model, IndentedStringBuilder builder)
    {
        string className = model.ClassName;

        foreach (XmlMemberModel member in model.AnnotatedMembers)
        {
            string accessKeyword = SyntaxFacts.GetText(member.PropertyAccessibility);
            string getterExpression = GetGetterExpression(member, className);

            if (!member.HasSetter)
            {
                // Getter-only: expression-bodied property
                builder.AppendLine($"{accessKeyword} partial {member.PropertyTypeDisplay} {member.PropertyName} => {getterExpression};");
            }
            else
            {
                // Getter + setter: block body
                string setterAccessKeyword = member.SetterAccessibility != member.PropertyAccessibility
                    ? SyntaxFacts.GetText(member.SetterAccessibility) + " "
                    : "";
                string setOrInit = member.IsInitOnly ? "init" : "set";

                builder.AppendLine($"{accessKeyword} partial {member.PropertyTypeDisplay} {member.PropertyName}");
                builder.AppendLine("{");
                IndentedStringBuilder inner = builder.IncreaseIndent();
                inner.AppendLine($"get => {getterExpression};");
                inner.AppendLine($"{setterAccessKeyword}{setOrInit} => {member.FieldName} = value;");
                builder.AppendLine("}");
            }
        }
    }

    private static string GetDefaultExpression(XmlMemberModel member)
    {
        if (member.DefaultValueExpression is { } defaultValue)
        {
            return defaultValue;
        }
        // Nullable fields (either naturally nullable or made nullable for null-check) use `default`
        // Value types also use `default` (which is the zero-value)
        return "default";
    }

    private static string GetGetterExpression(XmlMemberModel member, string className)
    {
        if (!member.RequiresNullCheck)
        {
            return member.FieldName;
        }
        if (member.IsStringType)
        {
            return $"{s_throwHelperPrefix}.{nameof(XmlFieldThrowHelper.NotNullOrEmpty)}({member.FieldName}, \"{className}\")";
        }
        return $"{s_throwHelperPrefix}.{nameof(XmlFieldThrowHelper.NotNull)}({member.FieldName}, \"{className}\")";
    }

    private static string RenderNamespace(string namespaceName) =>
        string.IsNullOrWhiteSpace(namespaceName)
            ? string.Empty
            : $"namespace {namespaceName};\n";
}
