using Microsoft.CodeAnalysis.CSharp;
using MoreInjuries.Roslyn.SourceGen.Extensions;
using MoreInjuries.Roslyn.SourceGen.XmlBinding.Attributes;
using System.Runtime.CompilerServices;
using System.Text;

namespace MoreInjuries.Roslyn.SourceGen.XmlBinding;

internal static class XmlBindingsRenderer
{
    private static readonly string s_throwHelperPrefix = $"global::{typeof(XmlFieldThrowHelper).FullName}";

    public static string Render(XmlBindableGenerationModel model)
    {
        StringBuilder sourceBuilder = new(
            $$"""
            // <auto-generated/>
            #nullable enable

            {{RenderNamespace(model.Namespace)}}
            partial class {{model.ClassName}}
            {

            """);

        IndentedStringBuilder indentedBuilder = new(sourceBuilder, indentLevel: 1);
        BuildFieldRegion(model, indentedBuilder);
        indentedBuilder.Raw.AppendLine();
        sourceBuilder.AppendLine("#pragma warning disable CS0618 // generated property accessors reference [Obsolete] backing fields");
        BuildPropertyRegion(model, indentedBuilder);
        sourceBuilder.AppendLine("#pragma warning restore CS0618");
        sourceBuilder.AppendLine("}");

        return sourceBuilder.ToString();
    }

    private static void BuildFieldRegion(XmlBindableGenerationModel model, IndentedStringBuilder builder)
    {
        foreach (XmlBindingModel member in model.AnnotatedMembers)
        {
            bool isReadonly = member.Setter is not { IsInitOnly: false };
            string readonlyModifier = isReadonly ? "readonly " : string.Empty;
            string defaultExpression = member.DefaultValueExpression ?? "default";

            builder.AppendLine($"[global::{typeof(CompilerGeneratedAttribute).FullName}]");
            if (!member.AllowRawAccess)
            {
                builder.AppendLine($"[global::{typeof(ObsoleteAttribute).FullName}(\"Do not use this field directly. Use the corresponding property instead.\", error: false)]");
            }
            builder.AppendLine($"private {readonlyModifier}{member.FieldTypeDisplay} {member.FieldName} = {defaultExpression};");
        }
    }

    private static void BuildPropertyRegion(XmlBindableGenerationModel model, IndentedStringBuilder builder)
    {
        string className = model.ClassName;

        foreach (XmlBindingModel member in model.AnnotatedMembers)
        {
            string accessKeyword = SyntaxFacts.GetText(member.PropertyAccessibility);
            string modifiers = member.PropertyModifiers;
            GetterPipelineModel pipeline = member.GetterPipeline;
            bool needsBlockGetter = pipeline.Transform is not null || pipeline.Validate is not null;

            if (!member.HasSetter && !needsBlockGetter)
            {
                // Simple getter-only: expression-bodied property
                string getterExpression = GetGetterExpression(member, className);
                builder.AppendLine($"{accessKeyword} {modifiers}partial {member.PropertyTypeDisplay} {member.PropertyName} => {getterExpression};");
            }
            else
            {
                // Block body property
                builder.AppendLine($"{accessKeyword} {modifiers}partial {member.PropertyTypeDisplay} {member.PropertyName}");
                builder.AppendLine("{");
                IndentedStringBuilder inner = builder.IncreaseIndent();

                if (needsBlockGetter)
                {
                    BuildBlockGetter(inner, member, className);
                }
                else
                {
                    string getterExpression = GetGetterExpression(member, className);
                    inner.AppendLine($"get => {getterExpression};");
                }

                if (member.Setter is { } setter)
                {
                    string setterAccessKeyword = setter.Accessibility != member.PropertyAccessibility
                        ? SyntaxFacts.GetText(setter.Accessibility) + " "
                        : string.Empty;
                    string setOrInit = setter.IsInitOnly ? "init" : "set";
                    string valueExpression = setter.CastType is { } castType
                        ? $"({castType})value"
                        : "value";
                    inner.AppendLine($"{setterAccessKeyword}{setOrInit} => this.{member.FieldName} = {valueExpression};");
                }

                builder.AppendLine("}");
            }
        }
    }

    private static void BuildBlockGetter(IndentedStringBuilder builder, XmlBindingModel member, string className)
    {
        builder.AppendLine("get");
        builder.AppendLine("{");
        IndentedStringBuilder inner = builder.IncreaseIndent();

        // Step 1: get base value (with null-check if needed)
        string baseExpression = GetGetterExpression(member, className);
        inner.AppendLine($"{member.PropertyTypeDisplay} __value = {baseExpression};");

        // Step 2: apply Transform if specified
        if (member.GetterPipeline.Transform is { } transform)
        {
            string callPrefix = transform.IsStatic ? string.Empty : "this.";
            inner.AppendLine($"__value = {callPrefix}{transform.MethodName}(__value);");
        }

        // Step 3: apply Validate if specified
        if (member.GetterPipeline.Validate is { } validate)
        {
            string callPrefix = validate.IsStatic ? string.Empty : "this.";
            inner.AppendLine($"if (!{callPrefix}{validate.MethodName}(__value))");
            inner.AppendLine("{");
            IndentedStringBuilder throwInner = inner.IncreaseIndent();
            throwInner.AppendLine($"{s_throwHelperPrefix}.{nameof(XmlFieldThrowHelper.FailedValidation)}(\"{className}\", \"{member.PropertyName}\");");
            inner.AppendLine("}");
        }

        inner.AppendLine("return __value;");
        builder.AppendLine("}");
    }

    private static string GetGetterExpression(XmlBindingModel member, string className)
    {
        GetterPipelineModel pipeline = member.GetterPipeline;
        if (!pipeline.RequiresNullCheck)
        {
            return $"this.{member.FieldName}";
        }
        if (pipeline.IsValueTypeNullCheck)
        {
            return $"{s_throwHelperPrefix}.{nameof(XmlFieldThrowHelper.ValueNotNull)}(this.{member.FieldName}, \"{className}\")";
        }
        if (pipeline.IsStringType)
        {
            return $"{s_throwHelperPrefix}.{nameof(XmlFieldThrowHelper.NotNullOrEmpty)}(this.{member.FieldName}, \"{className}\")";
        }
        return $"{s_throwHelperPrefix}.{nameof(XmlFieldThrowHelper.NotNull)}(this.{member.FieldName}, \"{className}\")";
    }

    private static string RenderNamespace(string namespaceName) =>
        string.IsNullOrWhiteSpace(namespaceName)
            ? string.Empty
            : $"namespace {namespaceName};\n";
}
