<!-- This file is imported by MoreInjuries.csproj to conditionally enable the Dubs Bad Hygiene integration. -->
<!-- To enable/disable, set the ModBadHygiene property in the main MoreInjuries.csproj file. -->
<Project>
    <!-- DLL reference requires _build\install-dependencies.ps1 to be run at least once to populate the dependencies folder. -->
    <ItemGroup Condition="'$(ModBadHygiene)'=='enable'">
        <Reference Include="BadHygiene">
            <HintPath>_build\dependencies\BadHygiene.dll</HintPath>
        </Reference>
    </ItemGroup>
    
    <!-- Conditional compilation setting for Dubs Bad Hygiene integration. -->
    <PropertyGroup Condition="'$(ModBadHygiene)'=='enable'">
        <DefineConstants>$(DefineConstants);MOD_BAD_HYGIENE</DefineConstants>
    </PropertyGroup>
    
    <ItemGroup Condition="'$(ModBadHygiene)'!='enable'">
        <Compile Remove="Integrations\DubsBadHygiene\**" />
        <None Include="Integrations\DubsBadHygiene\**" />
    </ItemGroup>
</Project>
