// <auto-generated/>
// injected into the compilation by the source generator
#nullable enable

namespace MoreInjuries.Roslyn.SourceGen.XmlBinding.Attributes;

/// <summary>
/// Provides throw helpers used by the XML serialization source generator to validate
/// that XML-bound backing fields have been initialized. This class is not intended
/// for direct use in application code.
/// </summary>
[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
internal static class XmlFieldThrowHelper
{
    [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
    private static void ThrowNull(string typeName, string? memberExpression) =>
        throw new global::System.InvalidOperationException(
            $"XML-bound member '{memberExpression}' of type '{typeName}' was not initialized. " +
            "Ensure the XML def provides a value for this field.");

    [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
    private static void ThrowNullOrEmpty(string typeName, string? memberExpression) =>
        throw new global::System.InvalidOperationException(
            $"XML-bound member '{memberExpression}' of type '{typeName}' was not initialized or is empty. " +
            "Ensure the XML def provides a non-empty value for this field.");

    [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
    private static void ThrowFailedValidation(string typeName, string propertyName) =>
        throw new global::System.InvalidOperationException(
            $"Validation failed for property '{propertyName}' of type '{typeName}'. " +
            "The value loaded from the XML def did not pass the configured validator.");

    /// <summary>
    /// Returns <paramref name="value"/> if it is not <see langword="null"/>; otherwise throws
    /// an <see cref="global::System.InvalidOperationException"/> indicating that the XML-bound field was not initialized.
    /// </summary>
    [return: global::System.Diagnostics.CodeAnalysis.NotNull]
    public static T NotNull<T>([global::System.Diagnostics.CodeAnalysis.NotNull] T? value, string typeName, [global::System.Runtime.CompilerServices.CallerArgumentExpression(nameof(value))] string? expression = null) where T : class
    {
        if (value is null)
        {
            ThrowNull(typeName, expression);
        }
        return value;
    }

    /// <summary>
    /// Returns the value of <paramref name="value"/> if it has one; otherwise throws
    /// an <see cref="global::System.InvalidOperationException"/> indicating that the XML-bound field was not initialized.
    /// </summary>
    public static T ValueNotNull<T>(T? value, string typeName, [global::System.Runtime.CompilerServices.CallerArgumentExpression(nameof(value))] string? expression = null) where T : struct
    {
        if (!value.HasValue)
        {
            ThrowNull(typeName, expression);
        }
        return value.GetValueOrDefault();
    }

    /// <summary>
    /// Returns <paramref name="value"/> if it is not <see langword="null"/> or empty; otherwise throws
    /// an <see cref="global::System.InvalidOperationException"/> indicating that the XML-bound field was not initialized.
    /// </summary>
    [return: global::System.Diagnostics.CodeAnalysis.NotNull]
    public static string NotNullOrEmpty([global::System.Diagnostics.CodeAnalysis.NotNull] string? value, string typeName, [global::System.Runtime.CompilerServices.CallerArgumentExpression(nameof(value))] string? expression = null)
    {
        if (value is null or { Length: 0 })
        {
            ThrowNullOrEmpty(typeName, expression);
        }
        return value;
    }

    /// <summary>
    /// Throws an <see cref="global::System.InvalidOperationException"/> indicating that the validator for
    /// the specified property returned <see langword="false"/>.
    /// </summary>
    [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
    public static void FailedValidation(string typeName, string propertyName) =>
        ThrowFailedValidation(typeName, propertyName);
}
