using System.Text;
using MoreInjuries.Roslyn.SourceGen.Extensions;
using MoreInjuries.Roslyn.SourceGen.XmlBinding.Models;

namespace MoreInjuries.Roslyn.SourceGen.XmlBinding.Rendering;

internal static class XmlBindingsRenderer
{
    public static string Render(XmlBindableGenerationModel model)
    {
        StringBuilder sourceBuilder = new(
            $$"""
            // <auto-generated/>
            #nullable enable

            {{RenderNamespace(model.Namespace)}}
            partial class {{model.ClassName}}
            {

            """);

        IndentedStringBuilder indentedBuilder = new(sourceBuilder, indentLevel: 1);
        XmlBindingFieldRenderer.BuildRegion(model, indentedBuilder);
        indentedBuilder.Raw.AppendLine();
        sourceBuilder.AppendLine("#pragma warning disable CS0618 // generated property accessors reference [Obsolete] backing fields");
        XmlBindingPropertyRenderer.BuildRegion(model, indentedBuilder);
        sourceBuilder.AppendLine("#pragma warning restore CS0618");
        sourceBuilder.AppendLine("}");

        return sourceBuilder.ToString();
    }

    private static string RenderNamespace(string namespaceName) =>
        namespaceName switch
        {
            _ when string.IsNullOrWhiteSpace(namespaceName) => string.Empty,
            _ => $"namespace {namespaceName};\n",
        };
}
