using MoreInjuries.Roslyn.SourceGen.Extensions;
using MoreInjuries.Roslyn.SourceGen.XmlBinding.Models;
using System.Text;

namespace MoreInjuries.Roslyn.SourceGen.XmlBinding.Rendering;

internal static class XmlBindingsRenderer
{
    public static string Render(XmlBindableGenerationModel model)
    {
        IndentedStringBuilder builder = new(new StringBuilder(), indentLevel: 0, indentSize: 4);
        builder.AppendLine(
            $$"""
            // <auto-generated/>
            #nullable enable

            {{RenderNamespace(model.Namespace)}}
            partial class {{model.ClassName}}
            {
            """);

        IndentedStringBuilder indentedBuilder = builder.IncreaseIndent();
        XmlBindingFieldRenderer.BuildRegion(model, indentedBuilder);
        indentedBuilder.AppendLine();
        builder.AppendLine("#pragma warning disable CS0618 // generated property accessors reference [Obsolete] backing fields");
        XmlBindingPropertyRenderer.BuildRegion(model, indentedBuilder);
        builder.AppendLine("#pragma warning restore CS0618");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static string RenderNamespace(string namespaceName) => string.IsNullOrWhiteSpace(namespaceName) ? string.Empty : $"namespace {namespaceName};\n";
}
