# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main", "rc-*" ]
  pull_request:
    branches: [ "main", "rc-*" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - name: Setup NuGet
      uses: nuget/setup-nuget@v2
    - name: Restore NuGet packages
      run: nuget restore Source\MoreInjuries\MoreInjuries.sln
    - name: Build project for release
      run: msbuild Source\MoreInjuries\MoreInjuries.sln -t:rebuild -property:Configuration=Release
    - name: Run unit tests
      run: dotnet test Source\MoreInjuries\MoreInjuries.sln
